-- =============================================================
-- Portfolio schema for Supabase
-- Run this in the Supabase SQL editor (Dashboard > SQL > New query)
-- It creates the tables, seeds them with the current content and
-- enables public read access for the anon key.
-- =============================================================

create extension if not exists "pgcrypto";
create extension if not exists "vector";

-- ---------------- profile (singleton row) ----------------
create table if not exists public.profile (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  alias text,
  status text,
  location text,
  started_coding text,
  focus text,
  email text,
  whatsapp text,
  instagram text,
  github text,
  roles text[] default '{}'::text[]
);

-- ---------------- stats ----------------
create table if not exists public.stats (
  id bigint generated by default as identity primary key,
  label text not null,
  value integer not null,
  suffix text default '',
  color text default 'green',
  sort_order integer default 0
);

-- ---------------- focus ----------------
create table if not exists public.focus (
  id bigint generated by default as identity primary key,
  num text not null,
  title text not null,
  text text not null,
  sort_order integer default 0
);

-- ---------------- experience ----------------
create table if not exists public.experience (
  id bigint generated by default as identity primary key,
  period text not null,
  role text not null,
  place text,
  type text,
  text text not null,
  tags text[] default '{}'::text[],
  sort_order integer default 0
);

-- ---------------- testimonials ----------------
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  quote text not null,
  name text not null,
  role text,
  rating integer default 5,
  sort_order integer default 0
);

-- ---------------- skills ----------------
create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  category text not null,
  skill text not null,
  level text default 'intermediate',
  percent integer default 70,
  sort_order integer default 0
);

-- ---------------- projects ----------------
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  preview text default '',
  tags text[] default '{}'::text[],
  source_url text,
  live_url text,
  sort_order integer default 0
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null,
  body text not null,
  category text default 'article',
  tags text[] default '{}'::text[],
  published_at date default current_date,
  sort_order integer default 0
);

-- =============================================================
-- Seed data
-- =============================================================

insert into public.profile (name, alias, status, location, started_coding, focus, email, whatsapp, instagram, github, roles)
values (
  'Byiringiro Elie',
  'M4STER',
  'Available for new opportunities',
  'Kigali, Rwanda',
  '2022 — and leveling up daily',
  'React + Node.js',
  'byiringiroelie468@gmail.com',
  '0783547443',
  'elie__001',
  'elie',
  array['Full-Stack Developer', 'Cybersecurity Analyst', 'API Architect']
)
on conflict do nothing;

insert into public.stats (label, value, suffix, color, sort_order) values
  ('Years Experience', 3, '+', 'green', 1),
  ('Projects Built', 6, '+', 'blue', 2),
  ('PageSpeed Score', 95, '+', 'cyan', 3)
on conflict do nothing;

insert into public.focus (num, title, text, sort_order) values
  ('01', 'Production-ready systems', 'Reliable applications built to run beyond a prototype.', 1),
  ('02', 'Secure API development', 'Protected, well-structured APIs with secure access control.', 2),
  ('03', 'Database architecture', 'Practical data models that stay maintainable as products grow.', 3),
  ('04', 'Penetration testing', 'Security testing mindset applied to every project.', 4),
  ('05', 'Real-time applications', 'Interactive experiences backed by dependable data flow.', 5),
  ('06', 'CI/CD pipelines', 'Repeatable delivery workflows that keep shipping consistent.', 6)
on conflict do nothing;

insert into public.experience (period, role, place, type, text, tags, sort_order) values
  (
    '2024 – Present',
    'Frontend Developer',
    'Freelance & product work · Kigali, Rwanda',
    'Full-time',
    'Building responsive web apps with HTML, CSS, JavaScript, and React. Focused on performance, accessibility, and modern UX patterns.',
    array['React', 'Node.js', 'CSS', 'JavaScript'],
    1
  ),
  (
    '2022 – 2024',
    'Cybersecurity Analyst',
    'Security operations · Kigali, Rwanda',
    'Full-time',
    'Securing web applications and APIs, performing penetration testing, vulnerability assessments, and implementing security best practices.',
    array['Pen Testing', 'API Security', 'Linux', 'Networking'],
    2
  )
on conflict do nothing;

insert into public.testimonials (quote, name, role, rating, sort_order) values
  (
    'The e-commerce platform transformed our checkout flow. Authentication, cart and payments all run reliably under real traffic. The work is solid and dependable.',
    'Ntirenganya Janvier',
    'Head of Product, TechSphere',
    5,
    1
  ),
  (
    'The store design and checkout flow brought our brand to life. The attention to detail is unmatched.',
    'Uwimana Yassin',
    'Lead Designer, CreativeFlow',
    5,
    2
  ),
  (
    'Working together was an absolute pleasure. The ability to translate complex ideas into clean, performant solutions is world-class.',
    'Elissa Ntihinduka',
    'Full Stack Developer, TechSolutions',
    5,
    3
  )
on conflict do nothing;

insert into public.skills (category, skill, level, percent, sort_order) values
  ('Languages', 'JavaScript', 'advanced', 92, 1),
  ('Languages', 'TypeScript', 'intermediate', 74, 2),
  ('Languages', 'HTML5', 'advanced', 90, 3),
  ('Languages', 'CSS3', 'advanced', 88, 4),
  ('Frontend', 'React', 'advanced', 90, 5),
  ('Frontend', 'Vite', 'intermediate', 76, 6),
  ('Frontend', 'Tailwind CSS', 'intermediate', 72, 7),
  ('Frontend', 'Responsive Design', 'advanced', 85, 8),
  ('Backend & Tools', 'Node.js', 'intermediate', 74, 9),
  ('Backend & Tools', 'Express', 'intermediate', 70, 10),
  ('Backend & Tools', 'Git / GitHub', 'advanced', 80, 11),
  ('Backend & Tools', 'REST APIs', 'intermediate', 78, 12),
  ('Cybersecurity', 'Penetration testing', 'applied', 68, 13),
  ('Cybersecurity', 'API security', 'applied', 72, 14),
  ('Cybersecurity', 'Secure access control', 'applied', 70, 15)
on conflict do nothing;

insert into public.projects (name, description, tags, sort_order) values
  ('E-commerce', 'Authentication, product management, cart & secure payments.', array['React', 'Node.js', 'MongoDB'], 1)
on conflict do nothing;

insert into public.posts (slug, title, excerpt, body, category, tags, published_at, sort_order) values
  (
    'structuring-a-react-node-full-stack-project',
    'How I Structure a React and Node.js Full-Stack Project',
    'A practical look at the folders, contracts and development workflow I use to keep a full-stack project understandable.',
    $post$Building a full-stack application used to feel like keeping too many ideas in my head at once. The frontend, the API, the database and deployment all had their own language, so it was easy to lose track of where a change belonged. I now begin every project by defining a clear boundary around each responsibility.

The first boundary is the data contract. Before writing components, I decide what the API will return and how each resource is identified. A small, predictable response shape prevents the frontend from guessing and makes the backend much easier to extend later.

On the React side, I keep the project focused around pages, reusable components, hooks and a small data layer. Components describe what the interface shows, while hooks coordinate fetching and state. This keeps visual code readable and gives data logic one clear place to live.

The Node.js service follows the same idea. Routes handle HTTP requests, controllers coordinate the work and service functions contain the business rules. A database repository can then be introduced without rewriting every route.

The final piece is a repeatable workflow: make one focused change, test the contract, verify the interface and commit the working result. Small steps make a large project feel manageable, and a clear structure makes future features cheaper to add.$post$,
    array['React', 'Node.js', 'Architecture'],
    '2026-08-21',
    1
  ),
  (
    'building-a-url-shortener-with-node-and-express',
    'Building a URL Shortener with Node.js and Express',
    'The design decisions behind creating short links, custom aliases, safe redirects and simple click analytics.',
    $post$A URL shortener looks tiny from the outside, but the interesting work happens behind the redirect. I wanted to understand the complete path from receiving a long URL to recording a visit, so I built the API as a small Express service with an intentionally narrow feature set.

Every shortened link receives a unique slug. When someone provides a custom alias, the server checks that it contains only safe characters and is not already taken. The database stores the destination, alias, creation time and click count, while the API returns the information a client actually needs.

The redirect route is intentionally small. It looks up the slug, increments the visit count and sends the user onward with a temporary redirect. If the alias does not exist, the service returns a clear not-found response instead of silently sending someone to the home page.

I also learned that input validation is part of the feature, not an extra step added later. Limits on URL length, alias length and request rate make the service easier to maintain and safer when it is connected to a public database.

What started as a simple REST API became a useful lesson in designing predictable contracts. Every endpoint does one job, errors are explicit and data validation happens before the database is touched.$post$,
    array['Node.js', 'Express', 'REST API'],
    '2026-07-30',
    2
  ),
  (
    'designing-a-fast-accessible-react-portfolio',
    'Designing a Fast and Accessible React Portfolio',
    'How thoughtful CSS, semantic markup and restrained animation can make a portfolio feel fast without becoming heavy.',
    $post$A portfolio should help visitors understand who created it within a few seconds. That means the page needs a strong visual hierarchy, readable typography and content that works before decorative effects load. For this site, performance and accessibility are part of the design rather than a final optimization pass.

I start with semantic HTML and a logical heading structure. Navigation uses real links, sections have clear labels and interactive elements remain keyboard accessible. These basics improve usability and also give assistive technology a better understanding of the page.

The visual system is built from a small set of design tokens. Shared colors, spacing, radii and transitions make the interface consistent, while theme variables allow the dark and light versions to change without duplicating entire sections. Most effects use transform and opacity so animation stays smooth.

Images need explicit dimensions to prevent layout shifts, and decorative backgrounds should never carry essential information. On smaller screens, the layout changes by content priority: identity first, navigation stays compact and cards move into a single readable column.

The result feels fast because the browser has less unnecessary work to do. Accessibility improves because the design works beyond color and motion. Good frontend work is not a layer added at the end; it is the discipline that shapes every component from the beginning.$post$,
    array['React', 'Performance', 'Accessibility'],
    '2026-07-08',
    3
  ),
  (
    'learning-full-stack-development-one-project-at-a-time',
    'Learning Full-Stack Development One Project at a Time',
    'A personal write-up about moving from first JavaScript lines to building complete products and publishing what I learn.',
    $post$My programming journey did not begin with a perfect plan. It began with curiosity and a willingness to make small things work. Early on, I followed tutorials, wrote simple layouts and repeatedly broke code while learning how the browser responded.

Projects changed the way I learn. A tutorial can show me the happy path, but building my own product forces me to decide what the data looks like, where responsibilities belong and what happens when a request fails. Every confusing problem becomes a practical lesson.

My first full-stack attempts were messy. Components held too much state, routes were difficult to extend and I changed database fields halfway through a feature. Those mistakes became useful because I could see exactly why the design was not working. Refactoring taught me more than quickly rewriting the same code again.

Publishing my progress also changed my mindset. A write-up forces me to explain not only what works, but why I chose it. If I cannot explain a decision clearly, I need to understand it better before moving on.

I am still early in this journey, but the pattern is clear: learn a concept, use it in a project, explain what was built and improve the next version. That loop turns coding from a collection of tutorials into a sustainable practice.$post$,
    array['Learning', 'Full-Stack', 'Growth'],
    '2026-06-12',
    4
  )
on conflict (slug) do nothing;

-- =============================================================
-- Security: allow public read, keep write locked down
-- =============================================================

alter table public.profile enable row level security;
alter table public.stats enable row level security;
alter table public.focus enable row level security;
alter table public.experience enable row level security;
alter table public.skills enable row level security;
alter table public.projects enable row level security;
alter table public.posts enable row level security;

do $$
declare t text;
begin
  foreach t in array array['profile', 'stats', 'focus', 'experience', 'testimonials', 'skills', 'projects', 'posts'] loop
    execute format('drop policy if exists "public read %s" on public.%I;', t, t);
    execute format('create policy "public read %s" on public.%I for select using (true);', t, t);
  end loop;
end $$;